import abiJson from "./abi.json";

// ── Contract: ILAwareLimitOrderHook ─────────────────────
// ABI is auto-generated by `forge build` from
// src/ILAwareLimitOrderHook.sol and copied here.
export const HOOK_ABI = abiJson.abi;

// ── StateView ABI (shared) ──────────────────────────────
export const STATE_VIEW_ABI = [
  {
    name: "getSlot0",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "poolId", type: "bytes32" }],
    outputs: [
      { name: "sqrtPriceX96", type: "uint160" },
      { name: "tick", type: "int24" },
      { name: "protocolFee", type: "uint24" },
      { name: "lpFee", type: "uint24" },
    ],
  },
  {
    name: "getLiquidity",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "poolId", type: "bytes32" }],
    outputs: [{ name: "liquidity", type: "uint128" }],
  },
] as const;

// ── Per-chain contract addresses ────────────────────────
// NOTE on token sorting:
//   Base:     WETH (0x4200...) < USDC (0x8335...) → currency0=WETH, currency1=USDC
//   Unichain: USDC (0x078d...) < WETH (0x4200...) → currency0=USDC, currency1=WETH
//   This affects price interpretation! See getChainContracts().wethIsCurrency0

type ChainContracts = {
  hook: `0x${string}`;
  stateView: `0x${string}`;
  poolManager: `0x${string}`;
  weth: { address: `0x${string}`; symbol: string; name: string; decimals: number };
  usdc: { address: `0x${string}`; symbol: string; name: string; decimals: number };
  poolId: `0x${string}`;
  explorerUrl: string;
  chainLabel: string;
  // true means currency0=WETH (like Base), false means currency0=USDC (like Unichain)
  wethIsCurrency0: boolean;
  // Vault UI copy — the on-chain yieldVault differs per chain: real Aave on Base, demo on Unichain.
  vaultLabel: string;
  vaultIsReal: boolean;
};

const CHAIN_CONTRACTS: Record<number, ChainContracts> = {
  // ── Base Mainnet (8453) ─────────────────────────────
  8453: {
    // DeployBaseAave — production hook wired to REAL Aave (waBasUSDC). Supersedes the old demo
    // hook 0x45d971BdE51dd5E109036aB70a4E0b0eD2Dc4040 (SimulatedYieldVault).
    hook: "0x17fE80F8a1ba277B1acd86D1622FaFC20CD254Ce",
    stateView: "0xa3c0c9b65bad0b08107aa264b0f3db444b867a71",
    poolManager: "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    weth: {
      address: "0x4200000000000000000000000000000000000006",
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
    },
    usdc: {
      address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
    },
    poolId: "0x2635acf3c8c698bea9a28853457930c14d6eceec348de6b87e1892e88e4b81f2",
    explorerUrl: "https://basescan.org",
    chainLabel: "BASE",
    wethIsCurrency0: true,
    vaultLabel: "real Aave USDC yield",
    vaultIsReal: true,
  },

  // ── Unichain Mainnet (130) ──────────────────────────
  // Redeployed via script/DeployHookathon.s.sol on 2026-05-19
  // SimulatedYieldVault: 0xceee912C708516624E9aC5581c8FCC93eA8eE79d
  // Pool init tx: 0x3a082b9cb10f1c632502396116cf2b62280509f98d68e52a6db12cba6104f5a4
  130: {
    hook: "0x8C19f1641946c662308000bB4E2Eaf684c81d4CE",
    stateView: "0x86e8631a016f9068c3f085faf484ee3f5fdee8f2",
    poolManager: "0x1F98400000000000000000000000000000000004",
    weth: {
      address: "0x4200000000000000000000000000000000000006",
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
    },
    usdc: {
      address: "0x078d782b760474a361dda0af3839290b0ef57ad6",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
    },
    poolId: "0xe1d695d4c147091549aeb6f9e78521a0184a1e7e272a71c12e708c881981f6ba",
    explorerUrl: "https://uniscan.xyz",
    chainLabel: "UNICHAIN",
    wethIsCurrency0: false,
    vaultLabel: "simulated 3% APY",
    vaultIsReal: false,
  },
};

// ── Default chain (Unichain — primary Hookathon target) ─
const DEFAULT_CHAIN_ID = 130;

// ── Getter: returns contracts for a given chainId ───────
export function getChainContracts(chainId: number | undefined): ChainContracts {
  return CHAIN_CONTRACTS[chainId ?? DEFAULT_CHAIN_ID] ?? CHAIN_CONTRACTS[DEFAULT_CHAIN_ID];
}

// ── Helper: get currency0/currency1 in Uniswap sort order ─
export function getSortedTokens(chainId: number | undefined) {
  const c = getChainContracts(chainId);
  if (c.wethIsCurrency0) {
    return { currency0: c.weth, currency1: c.usdc };
  }
  return { currency0: c.usdc, currency1: c.weth };
}

// ── Pool parameters (same on both chains) ───────────────
export const POOL_FEE = 3000;
export const TICK_SPACING = 60;

// ── Minimal ERC20 ABI ───────────────────────────────────
export const ERC20_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "symbol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
] as const;

// ── Supported chain IDs ─────────────────────────────────
export const SUPPORTED_CHAIN_IDS = Object.keys(CHAIN_CONTRACTS).map(Number);

// ── Is the connected chain one we have contracts for? ───
// getChainContracts() falls back to Unichain for unknown chains, so callers
// must use this to detect a wrong-network wallet (writes would otherwise be
// dispatched to the wallet's actual chain against Unichain addresses).
export function isSupportedChain(chainId: number | undefined): boolean {
  return chainId !== undefined && chainId in CHAIN_CONTRACTS;
}

// ── Vault disclosure ────────────────────────────────────
// The on-chain yieldVault differs per chain, so vault copy is per-chain (see each entry's
// `vaultLabel` / `vaultIsReal`): Base points at REAL Aave (waBasUSDC), while Unichain uses the
// demo SimulatedYieldVault (3% APY from block.timestamp). UI must not imply real yield on Unichain.